# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88787ce948ae2e1dc148b5495f1e5eb9c361a269c177b59c9b7b60618f01c2a74391b416006716b03850a24ac21925e3d632bca35b5581a1f53513bac8797f5a

test:
  secret_key_base: e77dd87c9cee4efb697b19382db4fefd142db1dd12b257d98922b8b3ebe5b072c4d5362244de6b62ce3fcff6771ef0121ce884833b51e7dc7e4f6a9e81e2d65b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
